// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sse

import (
	"gf-sse/api/sse"
)

type ControllerV1 struct{}

func NewV1() sse.ISseV1 {
	return &ControllerV1{}
}
