
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    pbentity:
      - link:   "mysql:root:123456@tcp(127.0.0.1:3306)/test?loc=Local&parseTime=true"
        tables: "device"
        gJsonSupport: "true"
    
    dao:
      - link:   "mysql:root:123456@tcp(127.0.0.1:3306)/test?loc=Local&parseTime=true"
        tables: "device"
        gJsonSupport: "true"