// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package file

import (
	"gf-upload/api/file"
)

type ControllerV1 struct{}

func NewV1() file.IFileV1 {
	return &ControllerV1{}
}
